---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: walden
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
    - "--dockerfile=Dockerfile"
    - "--context-sub-path=docker/trino"
    - "--context=git://github.com/scie-nz/walden.git"
    - "--destination=scienz/walden-trino"
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      projected:
        sources:
        - secret:
            name: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
  restartPolicy: Never
