apiVersion: v1
kind: Service
metadata:
  name: alluxio-web
  labels:
    app: alluxio-leader
spec:
{{- if .Values.alluxio.external_ip }}
  externalIPs:
  - {{ .Values.alluxio.external_ip }}
{{- end }}
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app: alluxio-leader
---
apiVersion: v1
kind: Service
metadata:
  name: alluxio
  labels:
    app: alluxio-leader
spec:
  ports:
  - name: rpc
    port: 19998
    targetPort: rpc
  - name: web
    port: 19999
    targetPort: web
  - name: job-rpc
    port: 20001
    targetPort: job-rpc
  - name: job-web
    port: 20002
    targetPort: job-web
  # These might not be necessary (only for HA leader?)
  - name: embedded
    port: 19200
  - name: job-embedded
    port: 20003
  selector:
    app: alluxio-leader
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alluxio-leader
  labels:
    app: alluxio-leader
spec:
  selector:
    matchLabels:
      app: alluxio-leader
  serviceName: alluxio-leader
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        app: alluxio-leader
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
      - name: journal-format
        image: {{ .Values.image.alluxio }}
        command: ["alluxio","formatJournal"]
        envFrom:
        - configMapRef:
            name: alluxio-config
        volumeMounts:
        - name: storage
          mountPath: /opt/alluxio/journal

      containers:

      - name: leader
        image: {{ .Values.image.alluxio }}
        command: ["tini", "--", "/entrypoint.sh"]
        args:
        - master-only
        - --no-format
        env:
        - name: ALLUXIO_MASTER_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ALLUXIO_MASTER_MOUNT_TABLE_ROOT_UFS
          value: {{ .Values.alluxio.root_mount }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: pass
        envFrom:
        - configMapRef:
            name: alluxio-config
        readinessProbe:
          tcpSocket:
            port: rpc
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: rpc
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
        ports:
        - name: rpc
          containerPort: 19998
        - name: web
          containerPort: 19999
        volumeMounts:
        - name: storage
          mountPath: /opt/alluxio/journal
{{- if and .Values.alluxio.nfs_server .Values.alluxio.nfs_path }}
        - name: nfs-data
          mountPath: /mnt/nfs
{{- end }}

      - name: job-leader
        image: {{ .Values.image.alluxio }}
        command: ["tini", "--", "/entrypoint.sh"]
        args:
        - job-master
        env:
        - name: ALLUXIO_MASTER_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ALLUXIO_MASTER_MOUNT_TABLE_ROOT_UFS
          value: {{ .Values.alluxio.root_mount }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: pass
        envFrom:
        - configMapRef:
            name: alluxio-config
        readinessProbe:
          tcpSocket:
            port: job-rpc
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: job-rpc
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
        ports:
        - name: job-rpc
          containerPort: 20001
        - name: job-web
          containerPort: 20002
        volumeMounts:
        - name: storage
          mountPath: /opt/alluxio/journal
{{- if and .Values.alluxio.nfs_server .Values.alluxio.nfs_path }}
        - name: nfs-data
          mountPath: /mnt/nfs
{{- end }}

      volumes:
{{- if and .Values.alluxio.nfs_server .Values.alluxio.nfs_path }}
      - name: nfs-data
        nfs:
          server: {{ .Values.alluxio.nfs_server }}
          path: {{ .Values.alluxio.nfs_path }}
{{- end }}

  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
