apiVersion: apps/v1
kind: Deployment
metadata:
  name: devserver
  namespace: walden
spec:
  selector:
    matchLabels:
      app: devserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devserver
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: scienz/walden-devserver
        name: devserver
        volumeMounts:
        - name: devserver-persistent-storage
          mountPath: /root
        resources:
          requests:
            memory: "2048Mi"
          limits:
            memory: "4096Mi"
        env:
          - name: HIVE_METASTORE_HOST
            value: metastore
          - name: HIVE_METASTORE_PORT
            value: "9083"
          - name: MINIO_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-root
                key: user
          - name: MINIO_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: minio-root
                key: pass
      volumes:
      - name: devserver-persistent-storage
        persistentVolumeClaim:
          claimName: devserver-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devserver-pvc
  namespace: walden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
