{{- if .Values.metastore.postgres.internal -}}
# from: https://github.com/helm/charts/issues/5167#issuecomment-641558251
{{-  $postgresUser := (randAlphaNum 40) | b64enc | quote -}}
{{-  $postgresPass := (randAlphaNum 40) | b64enc | quote -}}
{{-  $postgresSecret := (lookup "v1" "Secret" "walden" "metastore-postgres") -}}
{{-  if $postgresSecret -}}
{{-   $postgresUser = index $postgresSecret.data "user" -}}
{{-   $postgresPass = index $postgresSecret.data "pass" -}}
{{-  end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: metastore-postgres
  namespace: walden
  labels:
    app: metastore-postgres
type: Opaque
data:
  user: {{ $postgresUser }}
  pass: {{ $postgresPass }}
{{- end -}}
