apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: walden
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: bitnami/postgresql:latest
        name: postgres
        env:
        - name: POSTGRESQL_DATABASE
          value: metastore
        - name: POSTGRESQL_USERNAME
          value: metastore_user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metastore-postgres-pass
              key: pass
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /bitnami/postgresql
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: walden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore
  namespace: walden
data:
  metastore-site.xml.template: |-
{{ .Files.Get "configs/metastore-site.xml.template" | indent 4 }}
