# from: https://github.com/helm/charts/issues/5167#issuecomment-641558251
{{- $dbPass := (randAlphaNum 40) | b64enc | quote -}}
{{- $secret := (lookup "v1" "Secret" "walden" "metastore-postgres-pass") -}}
{{- if $secret -}}
{{-  $dbPass = index $secret.data "pass" -}}
{{- end -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: metastore-postgres-pass
  namespace: walden
  labels:
    app: postgres
type: Opaque
data:
  pass: {{ $dbPass }}
