---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: walden
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: walden
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - image: bitnami/postgresql:latest
        name: postgres
        env:
        - name: POSTGRESQL_DATABASE
          value: metastore
        - name: POSTGRESQL_USERNAME
          value: metastore_user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metastore-postgres-pass
              key: pass
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /bitnami/postgresql
        securityContext:
          runAsUser: 1001
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: walden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore
  namespace: walden
data:
  metastore-site.xml.template: |-
{{ .Files.Get "configs/metastore-site.xml.template" | indent 4 }}
---
# Hive standalone metastore, keeps track of table metadata.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metastore
  name: metastore
  namespace: walden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metastore
  strategy: {}
  template:
    metadata:
      labels:
        app: metastore
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: metastore
        image: scienz/walden-metastore:latest
        env:
          - name: POSTGRES_HOST
            value: postgres
          - name: METASTORE_PORT
            value: "9083"
          - name: POSTGRES_USER
            value: metastore_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: metastore-postgres-pass
                key: pass
          - name: POSTGRES_PORT
            value: "5432"
          - name: METASTORE_DB
            value: "metastore"
          - name: MINIO_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-root
                key: user
          - name: MINIO_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: minio-root
                key: pass
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9083
        resources: {}
        volumeMounts:
          - mountPath: /apache-hive-metastore-3.1.2-bin/metastore-site.xml.template
            name: config
            subPath: metastore-site.xml.template
            readOnly: false
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: metastore
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
# Hive Metastore service, exposes port 9083 to other services (Presto /
# Alluxio)
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metastore
  name: metastore
  namespace: walden
spec:
  ports:
  - port: 9083
  selector:
    app: metastore
status:
  loadBalancer: {}
---
