# from: https://github.com/helm/charts/issues/5167#issuecomment-641558251
{{- $rootUser := (randAlphaNum 20) | b64enc | quote -}}
{{- $rootPass := (randAlphaNum 40) | b64enc | quote -}}
{{- $secret := (lookup "v1" "Secret" "walden" "minio-root") -}}
{{- if $secret -}}
{{-  $rootUser = index $secret.data "user" -}}
{{-  $rootPass = index $secret.data "pass" -}}
{{- end -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-root
  namespace: walden
  labels:
    app: minio
type: Opaque
data:
  user: {{ $rootUser }}
  pass: {{ $rootPass }}
