---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: walden
  labels:
    app: minio
spec:
  ports:
  - name: s3
    port: 9000
    targetPort: s3
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: walden
  labels:
    app: minio
spec:
  ports:
  - name: s3
    port: 9000
    targetPort: s3
  clusterIP: None
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: walden
  labels:
    app: minio
spec:
  serviceName: minio-headless
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      # Minio is a good candidate for running on ARM when available.
      # However, Minio complains if we have mixed architectures, so lock it to only run on a single arch.
      nodeSelector:
        kubernetes.io/arch: {{ .Values.minio_arch }}
      # Run containers as nobody:nogroup
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: minio
        image: minio/minio:RELEASE.2022-02-05T04-40-59Z
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: pass
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - /bin/bash
        - -c
        # see https://docs.min.io/docs/distributed-minio-quickstart-guide.html
        - 'minio server http://minio-{0...3}.minio-headless.${NAMESPACE}.svc.cluster.local:9000/data'
        ports:
        - name: s3
          containerPort: 9000
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
