apiVersion: v1
kind: Service
metadata:
  name: superset-postgres
  namespace: walden
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: superset-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: superset-postgres
  namespace: walden
spec:
  serviceName: superset-postgres
  replicas: 1
  selector:
    matchLabels:
      app: superset-postgres
  template:
    metadata:
      labels:
        app: superset-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.1
        command:
        - bash
        - -c
        - 'mkdir -p $PGDATA
&& chown -R postgres:postgres "$PGDATA"
&& chmod 777 "$PGDATA"
&& /usr/local/bin/docker-entrypoint.sh postgres'
        env:
        - name: PGDATA
          value: /storage/postgres
        - name: POSTGRES_DB
          value: superset
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: superset-postgres
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: superset-postgres
              key: pass
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 60
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: storage
          mountPath: /storage
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
