# from: https://github.com/helm/charts/issues/5167#issuecomment-641558251
{{- $postgresUser := (randAlphaNum 40) | b64enc | quote -}}
{{- $postgresPass := (randAlphaNum 40) | b64enc | quote -}}
{{- $postgresSecret := (lookup "v1" "Secret" "walden" "superset-postgres") -}}
{{- if $postgresSecret -}}
{{-  $postgresUser = index $postgresSecret.data "user" -}}
{{-  $postgresPass = index $postgresSecret.data "pass" -}}
{{- end -}}

{{- $redisPass := (randAlphaNum 40) | b64enc | quote -}}
{{- $redisSecret := (lookup "v1" "Secret" "walden" "superset-redis") -}}
{{- if $redisSecret -}}
{{-  $redisPass = index $redisSecret.data "pass" -}}
{{- end -}}

{{- $supersetKey := (randAlphaNum 40) | b64enc | quote -}}
{{- $keySecret := (lookup "v1" "Secret" "walden" "superset-key") -}}
{{- if $keySecret -}}
{{-  $supersetKey = index $keySecret.data "secret_key" -}}
{{- end -}}

{{- $adminUser := (randAlphaNum 20) | b64enc | quote -}}
{{- $adminPass := (randAlphaNum 40) | b64enc | quote -}}
{{- if .Values.superset.username }}
{{-   $adminUser = .Values.superset.username | b64enc | quote -}}
{{- end }}
{{- if .Values.superset.password }}
{{-   $adminPass = .Values.superset.password | b64enc | quote -}}
{{- end }}
{{- $adminSecret := (lookup "v1" "Secret" "walden" "superset-admin") -}}
{{- if $adminSecret -}}
{{-  $adminUser = index $adminSecret.data "user" -}}
{{-  $adminPass = index $adminSecret.data "pass" -}}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: superset-postgres
  namespace: walden
  labels:
    app: superset-postgres
type: Opaque
data:
  user: {{ $postgresUser }}
  pass: {{ $postgresPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-redis
  namespace: walden
  labels:
    app: superset-redis
type: Opaque
data:
  pass: {{ $redisPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-key
  namespace: walden
  labels:
    app: superset
type: Opaque
data:
  secret_key: {{ $supersetKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-admin
  namespace: walden
  labels:
    app: superset
type: Opaque
data:
  user: {{ $adminUser }}
  pass: {{ $adminPass }}
