apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-worker
  namespace: walden
  labels:
    app: superset-worker
spec:
  replicas: {{ .Values.superset.worker_replicas }}
  selector:
    matchLabels:
      app: superset-worker
  template:
    metadata:
      labels:
        app: superset-worker
    spec:
      nodeSelector:
        # We only build an amd64 superset image
        kubernetes.io/arch: amd64
{{- if .Values.node.selector.superset_worker }}
{{ toYaml .Values.node.selector.superset_worker | indent 8 }}
{{- end }}
{{- if .Values.node.toleration.superset_worker }}
      tolerations:
{{ toYaml .Values.node.toleration.superset_worker | indent 8 }}
{{- end }}
      initContainers:

      - name: init-config
        image: {{ .Values.image.busybox }}
        command:
        - /bin/sh
        - /walden/superset_copy_configs.sh
        volumeMounts:
        - name: config
          mountPath: /out
        - name: config-walden
          mountPath: /walden
          readOnly: true
        - name: config-custom
          mountPath: /custom
          readOnly: true
        - name: secrets-custom
          mountPath: /secrets
          readOnly: true

      - name: wait-for-postgres
        image: {{ .Values.image.busybox }}
        command:
        - /bin/sh
        - -c
        - 'until nc -zv $POSTGRES_HOST $POSTGRES_PORT -w1; do echo waiting for postgres: ${POSTGRES_HOST}:${POSTGRES_PORT}; sleep 1; done'
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.superset.postgres.host }}
        - name: POSTGRES_PORT
          value: {{ .Values.superset.postgres.port | quote }}

      containers:

      - name: superset
        image: {{ .Values.image.superset }}
        command:
        - celery
        - --app=superset.tasks.celery_app:app
        - worker
        # might help with cleaning up zombie 'firefox-esr'/'WebExtensions'/'Web Content' processes?:
        - --pool=prefork
        - --max-tasks-per-child=128
        env:
        # Celery app invokes superset_config.py
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: superset-key
              key: secret_key
        - name: REDIS_HOST
          value: superset-redis
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: superset-redis
              key: pass
        - name: POSTGRES_HOST
          value: {{ .Values.superset.postgres.host }}
        - name: POSTGRES_PORT
          value: {{ .Values.superset.postgres.port | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.superset.postgres.db }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: superset-postgres
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: superset-postgres
              key: pass
        # Custom envvars for e.g. templated credentials in custom superset config
        {{- range .Values.superset.custom_env }}
        - {{ . | toJson }}
        {{- end }}
        resources:
          limits:
            memory: {{ .Values.superset.mem_limit_worker }}i # "nG" => "nGi"
        volumeMounts:
        - name: config
          mountPath: /app/pythonpath
          readOnly: true
      volumes:
      - name: config
        emptyDir: {}
      - name: config-walden
        configMap:
          name: superset
      - name: config-custom
        configMap:
          name: superset-custom
          optional: true
      - name: secrets-custom
        secret:
          secretName: superset-custom
          optional: true
