apiVersion: v1
kind: Service
metadata:
  name: superset-redis
  namespace: walden
  labels:
    app: superset-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: superset-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: superset-redis
  namespace: walden
  labels:
    app: superset-redis
spec:
  serviceName: superset-redis
  replicas: 1
  selector:
    matchLabels:
      app: superset-redis
  template:
    metadata:
      labels:
        app: superset-redis
    spec:
      # Doesn't strictly need to run on arm64
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: server
        image: {{ .Values.image.redis }}
        # Args are overrides of these settings:
        # https://raw.githubusercontent.com/antirez/redis/6.0/redis.conf
        command:
        - /bin/sh
        - -c
        - "redis-server \
--bind 0.0.0.0 \
--requirepass $REDIS_PASSWORD \
--loglevel $LOG_LEVEL \
--dir /data \
--maxmemory 100mb \
--maxmemory-policy allkeys-lru \
--lazyfree-lazy-eviction yes \
--lazyfree-lazy-expire yes \
--io-threads 3"
        env:
        - name: LOG_LEVEL
          value: "notice"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: superset-redis
              key: pass
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
