apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: walden
  labels:
    app: trino-coordinator
spec:
{{- if .Values.trino.external_ip }}
  externalIPs:
  - {{ .Values.trino.external_ip }}
{{- end }}
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: hivecache-data
    port: 8898
    targetPort: hivecache-data
  - name: hivecache-bk
    port: 8899
    targetPort: hivecache-bk
  # Custom ports for e.g. exposing additional hive caches
  {{- range $name, $port := .Values.trino.custom_ports }}
  - name: {{ $name }}
    port: {{ $port }}
    targetPort: {{ $name }}
  {{- end }}
  selector:
    app: trino-coordinator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-coordinator
  name: trino-coordinator
  namespace: walden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-coordinator
  template:
    metadata:
      labels:
        app: trino-coordinator
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
{{- if .Values.node.selector.trino_coordinator }}
{{ toYaml .Values.node.selector.trino_coordinator | indent 8 }}
{{- end }}
{{- if .Values.node.toleration.trino_coordinator }}
      tolerations:
{{ toYaml .Values.node.toleration.trino_coordinator | indent 8 }}
{{- end }}
      containers:
      - name: trino-coordinator
        image: {{ .Values.image.trino }}
        command:
        - /bin/bash
        - -c
        # Note: We currently generate a credentials file as an example.
        #       Trino requires that SSL be enabled before credentials can be used.
        - |
          mkdir -p /trino-server/etc/catalog &&
          cp -v /tmp/roconf/* /trino-server/etc &&
          cp -v /tmp/rocatalog/* /trino-server/etc/catalog &&
          htpasswd -c -b -B -C 10 /trino-server/etc/password.db "$TRINO_USER" "$TRINO_PASSWORD"
          /entrypoint.sh
        env:
        - name: HIVE_METASTORE_HOST
          value: metastore
        - name: HIVE_METASTORE_PORT
          value: "9083"
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: MINIO_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: pass
        - name: TRINO_USER
          valueFrom:
            secretKeyRef:
              name: trino-admin
              key: user
        - name: TRINO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trino-admin
              key: pass
        - name: CONFIG_JVM_HEAP
          value: "{{ .Values.trino.mem_jvm_heap }}"
        - name: CONFIG_QUERY_MAX_MEMORY_PER_NODE
          value: "{{ .Values.trino.config.query_max_memory_per_node }}"
        - name: CONFIG_QUERY_MAX_MEMORY
          value: "{{ .Values.trino.config.query_max_memory }}"
        - name: CONFIG_MEMORY_HEAP_HEADROOM_PER_NODE
          value: "{{ .Values.trino.config.memory_heap_headroom_per_node }}"
        - name: CONFIG_MAX_SPILL_PER_NODE
          value: "{{ .Values.trino.config.max_spill_per_node }}"
        - name: CONFIG_QUERY_MAX_SPILL_PER_NODE
          value: "{{ .Values.trino.config.query_max_spill_per_node }}"
        # Custom envvars for e.g. templated credentials in custom connector configs
        {{- range .Values.trino.custom_env }}
        - {{ . }}
        {{- end }}
        resources:
          limits:
            memory: {{ .Values.trino.mem_limit_coordinator }}i # "nG" => "nGi"
        ports:
        - name: http
          containerPort: 80
        - name: hivecache-data
          containerPort: 8898
        - name: hivecache-bk
          containerPort: 8899
        # Custom ports for e.g. exposing additional hive caches
        {{- range $name, $port := .Values.trino.custom_ports }}
        - name: {{ $name }}
          containerPort: {{ $port }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /tmp/roconf
        - name: catalog
          mountPath: /tmp/rocatalog
        - name: etc
          mountPath: /trino-server/etc
      volumes:
      - name: config
        configMap:
          name: trino-config
      - name: catalog
        configMap:
          name: trino-catalog
      - name: etc
        emptyDir: {}
