---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino
  namespace: walden
data:
  config.properties.template: |
{{ .Files.Get "configs/trino_config.properties.template" | indent 4 }}
  core-site.xml: |
{{ .Files.Get "configs/trino_core-site.xml" | indent 4 }}
  hive.properties: |
{{ .Files.Get "configs/trino_hive.properties" | indent 4 }}
  jvm.config: |
{{ .Files.Get "configs/trino_jvm.config" | indent 4 }}
  log.properties: |
{{ .Files.Get "configs/trino_log.properties" | indent 4 }}
  node.properties.template: |
{{ .Files.Get "configs/trino_node.properties.template" | indent 4 }}
  password-authenticator.properties: |
{{ .Files.Get "configs/trino_password-authenticator.properties" | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: walden
  labels:
    app: trino-coordinator
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: trino-coordinator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-coordinator
  name: trino-coordinator
  namespace: walden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-coordinator
  template:
    metadata:
      labels:
        app: trino-coordinator
    spec:
      nodeSelector:
        # We only build an amd64 trino image
        kubernetes.io/arch: amd64
      initContainers:
      - name: copy-ro-configs
        # Use walden-trino image, rather than busybox, to have access to htpasswd command
        image: {{ .Values.walden_docker_org }}/walden-trino:{{ .Values.walden_trino_tag }}
        command:
        - /bin/sh
        - -c
        # TODO We currently generate a credentials file but it's disabled until we can configure SSL for Trino.
        - |
          cp -v /conf/config.properties.template /conf/jvm.config /conf/node.properties.template /conf/password-authenticator.properties /conf-out/ &&
          mkdir -p /conf-out/catalog &&
          cp -v /conf/hive.properties /conf/core-site.xml /conf-out/catalog &&
          sed -i "s/__MINIO_ACCESS_KEY_ID/$MINIO_ACCESS_KEY_ID/g" /conf-out/catalog/hive.properties &&
          sed -i "s/__MINIO_ACCESS_KEY_SECRET/$MINIO_ACCESS_KEY_SECRET/g" /conf-out/catalog/hive.properties &&
          sed -i "s/__MINIO_ACCESS_KEY_ID/$MINIO_ACCESS_KEY_ID/g" /conf-out/catalog/core-site.xml &&
          sed -i "s/__MINIO_ACCESS_KEY_SECRET/$MINIO_ACCESS_KEY_SECRET/g" /conf-out/catalog/core-site.xml &&
          echo 'connector.name=tpch' > /conf-out/catalog/tpch.properties &&
          htpasswd -c -b -B -C 10 /conf-out/password.db "$TRINO_USER" "$TRINO_PASSWORD"
        env:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: MINIO_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: pass
        - name: TRINO_USER
          valueFrom:
            secretKeyRef:
              name: trino-admin
              key: user
        - name: TRINO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trino-admin
              key: pass
        volumeMounts:
        - name: configmap
          mountPath: /conf
        - name: pre-install
          mountPath: /conf-out
      containers:
      - name: trino-coordinator
        image: {{ .Values.walden_docker_org }}/walden-trino:{{ .Values.walden_trino_tag }}
        env:
        - name: HIVE_METASTORE_HOST
          value: metastore
        - name: HIVE_METASTORE_PORT
          value: "9083"
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: pre-install
          mountPath: /trino-server/etc
      volumes:
      - name: configmap
        configMap:
          name: trino
      - name: pre-install
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-worker
  name: trino-worker
  namespace: walden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: copy-ro-configs
        image: busybox
        command:
        - sh
        - -c
        - |
          cp -v /conf/config.properties.template /conf/jvm.config /conf/node.properties.template /conf-out/ &&
          mkdir -p /conf-out/catalog &&
          cp -v /conf/hive.properties /conf/core-site.xml /conf-out/catalog &&
          sed -i "s/__MINIO_ACCESS_KEY_ID/$MINIO_ACCESS_KEY_ID/g" /conf-out/catalog/hive.properties &&
          sed -i "s/__MINIO_ACCESS_KEY_SECRET/$MINIO_ACCESS_KEY_SECRET/g" /conf-out/catalog/hive.properties &&
          sed -i "s/__MINIO_ACCESS_KEY_ID/$MINIO_ACCESS_KEY_ID/g" /conf-out/catalog/core-site.xml &&
          sed -i "s/__MINIO_ACCESS_KEY_SECRET/$MINIO_ACCESS_KEY_SECRET/g" /conf-out/catalog/core-site.xml &&
          echo 'connector.name=tpch' > /conf-out/catalog/tpch.properties
        env:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: MINIO_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: pass
        volumeMounts:
        - name: properties
          mountPath: /conf
        - name: pre-install
          mountPath: /conf-out
      containers:
      - name: trino-worker
        image: {{ .Values.walden_docker_org }}/walden-trino:{{ .Values.walden_trino_tag }}
        env:
        - name: HIVE_METASTORE_HOST
          value: metastore
        - name: HIVE_METASTORE_PORT
          value: "9083"
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: pre-install
          mountPath: /trino-server/etc
      volumes:
      - name: properties
        configMap:
          name: trino
      - name: pre-install
        emptyDir: {}
