# These configmaps are shared by the trino coordinator and worker pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
  namespace: walden
data:
  # Configure 'hive' catalog that can be used for writing data in preinstalled MinIO and/or Alluxio
  # This is the "built-in" storage in Walden. Other supported types can be added by defining custom catalogs.
  core-site.xml: |
{{ .Files.Get "configs/trinocatalog_core-site.xml" | indent 4 }}
  hive.properties.template: |
{{ .Files.Get "configs/trinocatalog_hive.properties.template" | indent 4 }}

  # Enable TPCH benchmark schemas
  # See: https://trino.io/docs/current/connector/tpch.html
  tpch.properties: |
    connector.name=tpch

  # Enable JMX metrics schemas
  # See: https://trino.io/docs/current/connector/jmx.html
  jmx.properties: |
    connector.name=jmx

  # Any custom user catalog(s) for connecting to other data sources (e.g. cloud host object store).
  # Hive catalogs may require running multiple per-catalog Metastores.
  # User catalogs may use shell templating, see ../configs/*.template for examples.
{{- range $name, $props := .Values.trino.custom_catalogs }}
  {{ $name }}.properties.template: |
{{ $props | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  namespace: walden
data:
  config.properties.template: |
{{ .Files.Get "configs/trino_config.properties.template" | indent 4 }}
  postgres.properties: |
{{ .Files.Get "configs/trino_postgres.properties" | indent 4 }}
  jvm.config.template: |
{{ .Files.Get "configs/trino_jvm.config.template" | indent 4 }}
  log.properties: |
{{ .Files.Get "configs/trino_log.properties" | indent 4 }}
  node.properties.template: |
{{ .Files.Get "configs/trino_node.properties.template" | indent 4 }}
  password-authenticator.properties: |
{{ .Files.Get "configs/trino_password-authenticator.properties" | indent 4 }}
