# from: https://github.com/helm/charts/issues/5167#issuecomment-641558251
{{- $trinoUser := "walden" | b64enc | quote -}}
{{- $trinoPass := (randAlphaNum 40) | b64enc | quote -}}
{{- $adminSecret := (lookup "v1" "Secret" "walden" "trino-admin") -}}
{{- if $adminSecret -}}
{{-  $trinoUser = index $adminSecret.data "user" -}}
{{-  $trinoPass = index $adminSecret.data "pass" -}}
{{- end -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: trino-admin
  namespace: walden
  labels:
    app: trino-admin
type: Opaque
data:
  user: {{ $trinoUser }}
  pass: {{ $trinoPass }}
