databases:
- allow_run_async: true
  database_name: Trino (Walden)
  extra: '{"cost_estimate_enabled":true,"allows_virtual_table_explore":true,"metadata_params":{},"engine_params":{},"schemas_allowed_for_csv_upload":[]}'
  sqlalchemy_uri: trino://trino:8080
  tables: []
